# NumPy
***
## NumPyのインストール
***
`pip install numpy`

NumPyをJupyter Notebookで扱うときはpipでインストールしておかないといけない（Jupyter入れてたら一緒に入ってくるわけではない）
なお、仮想環境上で実行するのが一般的なので、
```
    python -m venv hoge
    ./hoge/Scripts/Activate.ps1
```
で仮想環境に入ろう。

## NumPyの使用
***
一般的には
`import numpy as np`
でインポートする

## 配列データを扱う
***

In [8]:
import numpy as np
a = np.array([1,2,3])
a.shape

(3,)

In [2]:
import numpy as np
b = np.array([[1,2,3], [4,5,6]])
b
b.shape

c1 = np.array([0,1,2,3,4,5])
c1

c2 = c1.reshape((2, 3)) #一次元配列を二次元配列(一行につき3要素)にする
"""
この要素数が均等に合わないようにするとValueErrorを返されてしまう。
"""
c2

c3 = c2.ravel() #二次元配列を一次元にしたものを「参照で」返す
c3

c4 = c2.flatten() #二次元配列を一次元にしたものを「コピーで」返す
c4

array([0, 1, 2, 3, 4, 5])

## 一次元配列の操作

In [17]:
import numpy as np
a = np.array([1,2,3])
a.dtype #データタイプを出力できる

d = np.array([1,2], dtype=np.int16) #明示的にデータタイプを指定可能
d.dtype #int16
d.astype(np.float16) #astypeで浮動小数点floatに変換可能
a[0] #配列指定可能
a[1:] #:をつければスライスで（後ろ全部）取得可能
a[-1] #負のインデックス指定可能

3

## 二次元配列の操作

In [26]:
import numpy as np

b = np.array([[1, 2, 3],
      [4, 5, 6]]) #([[],[],...])となることを忘れずに
b

b[0] #←一行目(1,2,3)の値を取得できる
b[1, 0] #←2行1列目を取得
b[:, 2] #3列目をすべて取得
b[1, :] #1行目をすべて取得

b[0, 1:] #取得する開始・終了範囲を指定することも出できる

b[:, [0, 2]] #すべての行の1列目、3列目を取得している

array([[1, 3],
       [4, 6]])

## 深いコピー
***
`変数1 = 変数2`とすると、変数を参照する形になるので、変数2が変わると変数1もかわる。

In [34]:
import numpy as np

a = np.array([1, 2, 3])
a1 = a
a1 #>aと同じarray([1, 2, 3])

a[0] = 4

a1 #これはarray([4, 2, 3])になる。7行目でaを変更したため。

a2 = a.copy()
a2 #aと同じものが入っている、当然。

a2[0] = 6
a2 #もちろんarray([6, 2, 3])

a #こちらは1要素目を6に変更したところは反映されていない。 array([4, 2, 3])

array([4, 2, 3])

## 配列の振り返り(変形におけるravelメソッドとflattenメソッド)
***

In [43]:
# import numpy as np

c = np.array([[0, 1, 2],
          [3, 4, 5]])
c1 = c.ravel() #参照で返す
c2 = c.flatten() #コピーで返す

c1
c2 #両方同じ出力

c1[0] = 6
c2[1] = 7

c1 #array([6, 1, 2, 3, 4, 5])
c2 #array([0, 7, 2, 3, 4, 5])

"""
array([[6, 1, 2],
       [3, 4, 5]])
となる。c1(参照)の影響を受けている形である。
"""
c

array([[6, 1, 2],
       [3, 4, 5]])

## Python標準スライスと、NumPyにおけるスライス
***
2つの出力結果には違いがある。
- Python標準：コピーが渡される
- NumPy：参照が渡される

In [54]:
import numpy as np

#標準のスライス

py_list1 = [0, 1]
py_list2 = py_list1[:] #スライス
py_list2[0] = 2

print("----標準のスライス----")
print("py_list1：" + str(py_list1))
print("py_list2：" + str(py_list2)) #標準のスライスにおいてはコピーが渡される。その証拠にpy_list1には変更が反映されていない。

#numpyにおけるスライス

np_array1 = np.array([0, 1])
np_array2 = np_array1[:]
np_array2[0] = 2

print("----NumPyにおけるスライス----")
print("np_array1：" + str(np_array1))
print("np_array2：" + str(np_array2)) #NumPyにおけるスライスでは参照が渡される。その証拠にnp_array1に変更が反映されている。(要素1が2になっている）

----標準のスライス----
py_list1：[0, 1]
py_list2：[2, 1]
----NumPyにおけるスライス----
np_array1：[2 1]
np_array2：[2 1]


## 数列を返す
***
Pythonのrange関数のような数列を作る関数がNumPyにもあります。
arrange関数でNumPy配列(ndarray)が生成される。
***

In [60]:
import numpy as np

np.arange(10) #順列を作成
np.arange(1,11) #開始地点や終了地点を指定できる。第2引数の一つ手前までの数値までの配列を生成できる。
np.arange(1, 11, 2) #第3引数で増分を指定できる

array([1, 3, 5, 7, 9])

## 乱数
***
NumPyの乱数発生関数は標準のrandom関数よりも高速に動作し、強力。

In [4]:
import numpy as np

f = np.random.random((3, 2))
f #3行2列のランダム配列を作成

np.random.seed(123) #シード値を固定することによって出力も固定できる。（テキストと同じ出力が出ている。）
np.random.random((3, 2))
#実際には乱数の固定は使わない

np.random.seed(123)
np.random.randint(1, 10) #1~10の間でランダムにintを出力(今回は3を出力)

np.random.seed(123)
np.random.randint(1, 10, (3, 3)) #第三引数で配列として行列数の指定ができる。
#106ページまで

np.random.seed(123)
np.random.uniform(0.0, 0.5, size=(2, 3)) #第一引数~第二引数で第三引数で指定した分の配列を返す。
#randintとの違いは小数値が返ってくるというところ

np.random.seed(123)
np.random.uniform(size=(4, 3)) #範囲の指定がないと0~1の範囲から配列を作成する

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

## 正規分布に従った乱数の出力
***
ここまでの乱数出力は一様乱数という範囲の中からランダムにピックアップするメソッドだった。
正規分布に従った乱数出力は`np.random.randn`を用いる。
***

In [9]:
import numpy as np

np.random.seed(123)
np.random.randn(4, 2) #正規分布に従って4*2の配列を出力する

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

## 同じ要素の数列を作る
***
zeros関数やones関数を用いて同じ要素が入った配列を生成できる
***

In [14]:
import numpy as np

np.zeros(3) #すべて0の配列を生成
np.zeros((2, 3))

np.ones(2)
np.ones((3, 4)) #すべて1の配列を生成

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 単位行列
***
eye関数を用いることで指定する体格要素を持った単位行列を作ることができる
***